# swagger.yml

openapi: 3.0.0
info:
  title: "2001 Trail API"
  description: "An API about trails and notes" 
  version: "1.0.0"

servers:
  - url: "/api"

components: 
  schemas:
    Trail:
      type: "object"
      required:
        - TrailID
      properties:
        TrailID:
          type: "integer"
        Trail_name:
          type: "string"
        Trail_Summary:
          type: "string"
        Trail_Description:
          type: "string"
        Difficulty:
          type: "string"
        Location:
          type: "string"
        Length:
          type: "integer"
        Elevation_gain:
          type: "integer"
        Route_type:
          type: "string"
        OwnerID:
          type: "integer"
    TUser:
      required:
        - UserID
      properties:
        UserID:
          type: "integer"
        Email_address: 
          type: "string"
        Role:
          type: "string"
  parameters:
    TrailID:
      name: "TrailID"
      description: "ID of trail to get"
      in: path
      required: True 
      schema:
        type: "integer"
    UserID:
      name: "UserID"
      description: "ID of the user"
      in: path
      required: True
      schema: 
        type: "integer"
      

paths:
  /trails:
    get:
      operationId: "trails.read_all"
      tags:
        - "Trails"
      summary: "Read the list of trails"
      responses:
        "200":
          description: "Successfully read trails list"
    post:
      operationId: "trails.create"
      tags:
        - Trails
      summary: "Create a trail"
      requestBody:
        description: "Trail to create"
        required: True 
        content: 
          application/json:
            schema:
              x-body-name: "trails"
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Successfully created trail"
  /trails/{TrailID}:
    get:
      operationId: "trails.read_one"
      tags:
        - Trails 
      summary: "Read one trail"
      parameters: 
        - $ref: "#/components/parameters/TrailID"
      responses:
        "200":
          description: "Successfully read Trail"
    put:
      tags:
        - Trails
      operationId: "trails.update"
      summary: "update a trail"
      parameters:
        - $ref: "#/components/parameters/TrailID"
      responses:
        "200":
          description: "Successfully updated trail"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "trails"
              $ref: "#/components/schemas/Trail"
    delete:
      tags:
        - Trails
      operationId: "trails.delete"
      summary: "Delete a trail"
      parameters:
        - $ref: "#/components/parameters/TrailID"
      responses:
        "204":
          description: "Successfully deleted trail"
  /TUser:
    get:
      operationId: "users.create"
      tags: 
        - Users
      summary: "Create a user "
      requestBody:
        description: "User to create" 
        required: True
        content:
         application/json:
          schema:
            x-body-name: "TUser"
            $ref: "#/components/schemas/TUser"
      responses:
        "201":
          description: "Successfully created user"

  /TUser/{UserID}:
    get:
      operationId: "users.read_one"
      tags:
        - Users
      summary: "Read one user"
      parameters:
        - $ref: "#/components/parameters/UserID"
      responses:
        "200":
          description: "Successfully read one User"
    put:
      tags:
        - Users
      operationId: "users.update"
      summary: "update a user"
      parameters:
        - $ref: "#/components/parameters/UserID"
      responses:
        "200":
          description: "Successfully updated user"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "tuser"
              type: "object"
              properties:
                content:
                 type: "string"
    delete:
      tags:
        - Users
      operationId: "users.delete"
      summary: "Delete a user"
      parameters: 
        - $ref: "#/components/parameters/UserID"
      responses:
        "204" :
          description: "Successfully deleted note"